/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.GuestBUS;
import DTO.GuestDTO;
import java.awt.Frame;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author taipham
 */
public class QLKhachThueTroGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form QLNguoiThueTroGUI
     */
    private GuestDTO _guestDTO;
    public static GuestBUS _guestBUS;
    private static ArrayList<GuestDTO> _listGuest;
    private DefaultTableModel _tableModel;

    public QLKhachThueTroGUI() {
        initComponents();
        this.setName("Khách trọ");
        tbGuest.setFillsViewportHeight(true);
        _guestDTO = new GuestDTO();
        _guestBUS = new GuestBUS();
        _listGuest = _guestBUS.getAllGuest();
        _tableModel = (DefaultTableModel) tbGuest.getModel();
        showTabelGuest(_listGuest);
        btnSaveGuest.setEnabled(false);
        btnCancelGuest.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cbTypeFind = new javax.swing.JComboBox<>();
        tfInputFindGuest = new javax.swing.JTextField();
        btnFindGuest = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnInsertGuest = new javax.swing.JButton();
        btnDeleteGuest = new javax.swing.JButton();
        btnEditGuest = new javax.swing.JButton();
        btnSaveGuest = new javax.swing.JButton();
        btnCancelGuest = new javax.swing.JButton();
        btnResetKhachThue = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbGuest = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfGuestID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfGuestName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spDob = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        cbCountrySide = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        tfJob = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfPhoneNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfPermanentAddress = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbSex = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tfNumberID = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("QUẢN LÍ KHÁCH THUÊ TRỌ");

        jPanel3.setBackground(new java.awt.Color(138, 213, 55));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jLabel11.setText("Tìm kiếm theo:");

        cbTypeFind.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên khách trọ", "Mã khách trọ", "Quê quán", "Nghề nghiệp", "Số điện thoại" }));

        btnFindGuest.setText("Tìm kiếm");
        btnFindGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindGuestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTypeFind, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 190, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfInputFindGuest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFindGuest)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbTypeFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfInputFindGuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindGuest))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(138, 213, 55));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        btnInsertGuest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_themkhach.png"))); // NOI18N
        btnInsertGuest.setText("Thêm");
        btnInsertGuest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInsertGuest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInsertGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertGuestActionPerformed(evt);
            }
        });

        btnDeleteGuest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_xoa.png"))); // NOI18N
        btnDeleteGuest.setText("Xóa");
        btnDeleteGuest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteGuest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeleteGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteGuestActionPerformed(evt);
            }
        });

        btnEditGuest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_sua.png"))); // NOI18N
        btnEditGuest.setText("Sửa");
        btnEditGuest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditGuest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditGuestActionPerformed(evt);
            }
        });

        btnSaveGuest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_save.png"))); // NOI18N
        btnSaveGuest.setText("Lưu");
        btnSaveGuest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaveGuest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSaveGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveGuestActionPerformed(evt);
            }
        });

        btnCancelGuest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_huy.png"))); // NOI18N
        btnCancelGuest.setText("Hủy");
        btnCancelGuest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelGuest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelGuestActionPerformed(evt);
            }
        });

        btnResetKhachThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_reset.png"))); // NOI18N
        btnResetKhachThue.setText("Reset");
        btnResetKhachThue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResetKhachThue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnResetKhachThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetKhachThueActionPerformed(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_thoat.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInsertGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnDeleteGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnEditGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnSaveGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnCancelGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnResetKhachThue, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInsertGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetKhachThue, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(138, 213, 55));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách khách trọ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        tbGuest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã khách trọ", "Tên khách trọ", "Phái", "Ngày sinh", "Quê quán", "CMND", "Địa chỉ thường trú", "Nghề nghiệp", "Điện thoại", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGuestMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbGuest);
        if (tbGuest.getColumnModel().getColumnCount() > 0) {
            tbGuest.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbGuest.getColumnModel().getColumn(0).setMaxWidth(40);
            tbGuest.getColumnModel().getColumn(1).setPreferredWidth(100);
            tbGuest.getColumnModel().getColumn(1).setMaxWidth(100);
            tbGuest.getColumnModel().getColumn(3).setPreferredWidth(50);
            tbGuest.getColumnModel().getColumn(3).setMaxWidth(50);
            tbGuest.getColumnModel().getColumn(4).setPreferredWidth(100);
            tbGuest.getColumnModel().getColumn(4).setMaxWidth(100);
            tbGuest.getColumnModel().getColumn(5).setPreferredWidth(100);
            tbGuest.getColumnModel().getColumn(5).setMaxWidth(100);
            tbGuest.getColumnModel().getColumn(6).setPreferredWidth(100);
            tbGuest.getColumnModel().getColumn(6).setMaxWidth(100);
            tbGuest.getColumnModel().getColumn(8).setPreferredWidth(100);
            tbGuest.getColumnModel().getColumn(8).setMaxWidth(100);
            tbGuest.getColumnModel().getColumn(9).setPreferredWidth(100);
            tbGuest.getColumnModel().getColumn(9).setMaxWidth(100);
            tbGuest.getColumnModel().getColumn(10).setPreferredWidth(100);
            tbGuest.getColumnModel().getColumn(10).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(138, 213, 55));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách thuê trọ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jLabel1.setText("Mã khách trọ:");

        jLabel3.setText("Tên khách trọ: ");

        jLabel4.setText("Ngày sinh:");

        spDob.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_WEEK));
        spDob.setEditor(new javax.swing.JSpinner.DateEditor(spDob, "dd/MM/yyyy"));

        jLabel5.setText("Quê quán:");

        cbCountrySide.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TP Hà Nội", "TP Hồ Chí Minh", "Tỉnh An Giang", "Tỉnh Bà Rịa - Vũng Tàu", "Tỉnh Bạc Liêu", "Tỉnh Bắc Giang", "Tỉnh Bắc Kạn", "Tỉnh Bắc Ninh", "Tỉnh Bến Tre", "Tỉnh Bình Dương", "Tỉnh Bình Định", "Tỉnh Bình Phước", "Tỉnh Bình Thuận", "Tỉnh Cao Bằng", "Tỉnh Cà Mau", "TP Cần Thơ", "TP Hải Phòng", "TP Đà Nẵng", "Tỉnh Gia Lai", "Tỉnh Hòa Bình", "Tỉnh Hà Giang", "Tỉnh Hà Nam", "Tỉnh Hà Tĩnh", "Tỉnh Hưng Yên", "Tỉnh Hải Dương", "Tỉnh Hậu Giang", "Tỉnh Điện Biên ", "Tỉnh Đắk Lắk", "Tỉnh Đắk Nông", "Tỉnh Đồng Nai", "Tỉnh Đồng Tháp", "Tỉnh Khánh Hòa", "Tỉnh Kiên Giang", "Tỉnh Kon Tum", "Tỉnh Lai Châu", "Tỉnh Long An", "Tỉnh Lào Cai", "Tỉnh Lâm Đồng", "Tỉnh Lạng Sơn", "Tỉnh Nam Định", "Tỉnh Nghệ An", "Tỉnh Ninh Bình", "Tỉnh Ninh Thuận", "Tỉnh Phú Thọ", "Tỉnh Phú Yên", "Tỉnh Quảng Bình", "Tỉnh Quảng Nam ", "Tỉnh Quảng Ngãi", "Tỉnh Quảng Ninh", "Tỉnh Quảng Trị", "Tỉnh Sóc Trăng", "Tỉnh Sơn La", "Tỉnh Thanh Hóa", "Tỉnh Thái Bình", "Tỉnh Thái Nguyên", "Tỉnh Thừa Thiên - Huế", "Tỉnh Tiền Giang", "Tỉnh Trà Vinh", "Tỉnh Tuyên Quang", "Tỉnh Tây Ninh", "Tỉnh Vĩnh Long", "Tỉnh Vĩnh Phúc", "Tỉnh Yên Bái" }));

        jLabel9.setText("Nghề nghiệp:");

        jLabel13.setText("Điện thoại:");

        jLabel7.setText("Đ/c thường trú: ");

        jLabel10.setText("Phái:");

        cbSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));

        jLabel6.setText("Số CMND:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNumberID)
                    .addComponent(tfGuestID, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfGuestName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(cbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfPermanentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spDob, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJob, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel5))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfPhoneNumber)
                    .addComponent(cbCountrySide, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfGuestID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCountrySide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(cbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(tfGuestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(tfNumberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(tfJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfPermanentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(535, 535, 535)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static public void updateStateGuestGUI(String guestID) {
        int totalRow = tbGuest.getRowCount();
        for (GuestDTO guest : _listGuest) {
            if (guest.getGuestID().equals(guestID)) {
                guest.setStateGuest(1);
                break;
            }
        }

        for (int i = 0; i < totalRow; ++i) {
            if (tbGuest.getValueAt(i, 1).equals(guestID)) {
                tbGuest.setValueAt("Đã thuê", i, 10);
                break;
            }
        }
    }

    //lay danh sach khach tro
    static public ArrayList<GuestDTO> getListGuest() {
        return _listGuest;
    }

    // in trang thai
    public String getStatusGuest(int i) {
        return i == 1 ? "Đã thuê" : "Chưa thuê";
    }

    //load table
    public void showTabelGuest(ArrayList<GuestDTO> listGuest) {
        int i = 1;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        for (GuestDTO guest : listGuest) {
            _tableModel.addRow(new Object[]{
                i++, guest.getGuestID(), guest.getGuestName(), guest.getSex(), sdf.format(guest.getDob()), guest.getCountrySide(), guest.getNumberID(),
                guest.getPermanentAddress(), guest.getJob(), guest.getPhoneNumber(), getStatusGuest(guest.getStateGuest())
            });
        }
    }

    //load table update
    public void showTableGuestUpdate() {
        int i = tbGuest.getRowCount() + 1;
        _guestDTO = _listGuest.get(_listGuest.size() - 1);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        _tableModel.addRow(new Object[]{
            i, _guestDTO.getGuestID(), _guestDTO.getGuestName(), _guestDTO.getSex(), sdf.format(_guestDTO.getDob()), _guestDTO.getCountrySide(), _guestDTO.getNumberID(),
            _guestDTO.getPermanentAddress(), _guestDTO.getJob(), _guestDTO.getPhoneNumber(), getStatusGuest(_guestDTO.getStateGuest())
        });
    }

    //kiem tra thong tin truoc khi them
    public boolean checkInfo() {
        if (tfGuestID.getText().length() == 0 || tfGuestName.getText().length() == 0 || tfNumberID.getText().length() == 0) {
            return false;
        }
        return true;
    }

    //sự kiện bấm nút thêm
    private void btnInsertGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertGuestActionPerformed
        if (!checkInfo()) {
            JOptionPane.showMessageDialog(this, "Hãy điền đủ thông tin", "Thêm khách trọ", JOptionPane.ERROR_MESSAGE);
            return;
        }
        _guestDTO.setGuestID(tfGuestID.getText());
        _guestDTO.setGuestName(tfGuestName.getText());
        _guestDTO.setSex(cbSex.getSelectedItem().toString());
        _guestDTO.setDob((Date) spDob.getValue());
        _guestDTO.setCountrySide(cbCountrySide.getSelectedItem().toString());
        _guestDTO.setNumberID(tfNumberID.getText());
        _guestDTO.setPermanentAddress(tfPermanentAddress.getText());
        _guestDTO.setJob(tfJob.getText());
        _guestDTO.setPhoneNumber(tfPhoneNumber.getText());
        _guestDTO.setStateGuest(0);

        if (_guestBUS.insertGuest(_guestDTO)) {
            JOptionPane.showMessageDialog(this, "Thêm vào database thành công", "Thêm khách trọ", JOptionPane.INFORMATION_MESSAGE);
            _listGuest.add(_guestDTO);
            showTableGuestUpdate();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm vào database thất bại", "Thêm khách trọ", JOptionPane.ERROR_MESSAGE);
        }
        reset();
        DangKiThuePhongGUI.showTableGuestDontHaveRoom(_listGuest);
    }//GEN-LAST:event_btnInsertGuestActionPerformed

    //tim kiem khach tro trong listguest
    public int getIndexListGuest(String guestId) {
        int len = _listGuest.size();
        for (int i = 0; i < len; ++i) {
            if (_listGuest.get(i).getGuestID().equals(guestId)) {
                return i;
            }
        }
        return -1;
    }

    //su kien bam nut xoa
    private void btnDeleteGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteGuestActionPerformed
        int[] vt = tbGuest.getSelectedRows();
        int index = -1;
        if (vt.length > 0) {
            for (int i = vt.length - 1; i >= 0; --i) {
                index = getIndexListGuest(tbGuest.getValueAt(vt[i], 1).toString());
                if (_listGuest.get(index).getStateGuest() == 0) {
                    if (!_guestBUS.deleteGuest(_listGuest.get(index).getGuestID(), _listGuest.get(index).getStateGuest())) {
                        JOptionPane.showMessageDialog(this, "Xóa dữ liệu trong database thất bại", "Xóa khách trọ", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    _listGuest.remove(index);
                } else {
                    JOptionPane.showMessageDialog(this, "Khach trọ đang thuê, không được xóa", "Xóa khách trọ", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            JOptionPane.showMessageDialog(this, "Xóa dữ liệu trong database thành công", "Xóa khách trọ", JOptionPane.INFORMATION_MESSAGE);
            _tableModel.setRowCount(0);
            showTabelGuest(_listGuest);
            DangKiThuePhongGUI.showTableGuestDontHaveRoom(_listGuest);
        } else {
            JOptionPane.showMessageDialog(this, "Hãy chọn khách trọ chưa đăng kí thuê trọ muốn xóa", "Xóa khách trọ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteGuestActionPerformed

    //su kien bam nut sua thong tin khach thue
    private void btnEditGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditGuestActionPerformed
        setEnable(true);
        tfGuestID.setEnabled(false);
        btnSaveGuest.setEnabled(true);
        btnCancelGuest.setEnabled(true);
        btnDeleteGuest.setEnabled(false);
    }//GEN-LAST:event_btnEditGuestActionPerformed

    //set Enable
    public void setEnable(boolean bool) {
        tfGuestID.setEnabled(bool);
        tfGuestName.setEnabled(bool);
        cbSex.setEnabled(bool);
        spDob.setEnabled(bool);
        cbCountrySide.setEnabled(bool);
        tfNumberID.setEnabled(bool);
        tfPermanentAddress.setEnabled(bool);
        tfJob.setEditable(bool);
        tfPhoneNumber.setEnabled(bool);
    }

    //su kien nhap vao dong trong bang
    private void tbGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGuestMouseClicked
        int vt = tbGuest.getSelectedRow();
        SimpleDateFormat sp = new SimpleDateFormat("dd/MM/yyyy");
        if (vt != -1) {
            tfGuestID.setText(tbGuest.getValueAt(vt, 1).toString());
            tfGuestName.setText(tbGuest.getValueAt(vt, 2).toString());
            cbSex.getModel().setSelectedItem(tbGuest.getValueAt(vt, 3).toString());
            try {
                spDob.getModel().setValue(sp.parse(tbGuest.getValueAt(vt, 4).toString()));
            } catch (ParseException ex) {
                Logger.getLogger(QLKhachThueTroGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            cbCountrySide.getModel().setSelectedItem(tbGuest.getValueAt(vt, 5));
            tfNumberID.setText(tbGuest.getValueAt(vt, 6).toString());
            tfPermanentAddress.setText(tbGuest.getValueAt(vt, 7).toString());
            tfJob.setText(tbGuest.getValueAt(vt, 8).toString());
            tfPhoneNumber.setText(tbGuest.getValueAt(vt, 9).toString());

        }
        btnInsertGuest.setEnabled(false);
        setEnable(false);
    }//GEN-LAST:event_tbGuestMouseClicked

    //reset thong tin
    public void reset() {
        Date date = new Date();
        setEnable(true);
        btnInsertGuest.setEnabled(true);
        btnSaveGuest.setEnabled(false);
        btnCancelGuest.setEnabled(false);
        btnDeleteGuest.setEnabled(true);
        tbGuest.clearSelection();
        tfGuestID.setText("");
        tfGuestName.setText("");
        cbSex.setSelectedIndex(0);
        spDob.getModel().setValue(date);
        cbCountrySide.setSelectedIndex(0);
        tfNumberID.setText("");
        tfPermanentAddress.setText("");
        tfJob.setText("");
        tfPhoneNumber.setText("");
        cbTypeFind.setSelectedIndex(0);
        tfInputFindGuest.setText("");
    }

    //su kien nhap nut luu
    private void btnSaveGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveGuestActionPerformed
        int vt = tbGuest.getSelectedRow();
        if (vt != -1) {
            _guestDTO = _listGuest.get(getIndexListGuest(tbGuest.getValueAt(vt, 1).toString()));
            _guestDTO.setGuestName(tfGuestName.getText());
            _guestDTO.setSex(cbSex.getSelectedItem().toString());
            _guestDTO.setDob((Date) spDob.getValue());
            _guestDTO.setCountrySide(cbCountrySide.getSelectedItem().toString());
            _guestDTO.setNumberID(tfNumberID.getText());
            _guestDTO.setPermanentAddress(tfPermanentAddress.getText());
            _guestDTO.setJob(tfJob.getText());
            _guestDTO.setPhoneNumber(tfPhoneNumber.getText());

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            if (_guestBUS.updateGuest(_guestDTO)) {
                JOptionPane.showMessageDialog(this, "Update vào database thành công", "Update khach trọ", JOptionPane.INFORMATION_MESSAGE);
                //set lai gia tri moi cho cot
                tbGuest.setValueAt(_guestDTO.getGuestName(), vt, 2);
                tbGuest.setValueAt(_guestDTO.getSex(), vt, 3);
                tbGuest.setValueAt(sdf.format(_guestDTO.getDob()), vt, 4);
                tbGuest.setValueAt(_guestDTO.getCountrySide(), vt, 5);
                tbGuest.setValueAt(_guestDTO.getNumberID(), vt, 6);
                tbGuest.setValueAt(_guestDTO.getPermanentAddress(), vt, 7);
                tbGuest.setValueAt(_guestDTO.getJob(), vt, 8);
                tbGuest.setValueAt(_guestDTO.getNumberID(), vt, 9);
            } else {
                JOptionPane.showMessageDialog(this, "Update vào database thất bại", "Update khách trọ", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        reset();
        DangKiThuePhongGUI.showTableGuestDontHaveRoom(_listGuest);
    }//GEN-LAST:event_btnSaveGuestActionPerformed

    //su kien bam nut huy
    private void btnCancelGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelGuestActionPerformed
        reset();
    }//GEN-LAST:event_btnCancelGuestActionPerformed

    //su kien bam nut reset
    private void btnResetKhachThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetKhachThueActionPerformed
        reset();
    }//GEN-LAST:event_btnResetKhachThueActionPerformed

    //su kien nhap nut tim kiem
    private void btnFindGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindGuestActionPerformed
        String type = cbTypeFind.getSelectedItem().toString();
        String input = tfInputFindGuest.getText();
        if (input.length() == 0) {
            JOptionPane.showMessageDialog(this, "Hãy điền thông tin tìm kiếm", "Tìm kiếm", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JFrame tmp = new JFrame();
        FindGuestDialog findDialog = new FindGuestDialog(tmp, true);
        switch (type) {
            case "Tên khách trọ":
                type = "TenKhachTro";
                break;
            case "Mã khách trọ":
                type = "MaKhachTro";
                break;
            case "Quê quán":
                type = "QueQuan";
                break;
            case "Nghề nghiệp":
                type = "NgheNghiep";
                break;
            case "Điện thoại":
                type = "DienThoai";
                break;
        }

        if (type.equals("TenKhachTro")) {
            findDialog.showTable(_guestBUS.findGuestByName(input));
            findDialog.setVisible(true);
        } else {
            findDialog.showTable(_guestBUS.findGuestBy(type, input));
            findDialog.setVisible(true);
        }
    }//GEN-LAST:event_btnFindGuestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelGuest;
    private javax.swing.JButton btnDeleteGuest;
    private javax.swing.JButton btnEditGuest;
    private javax.swing.JButton btnFindGuest;
    private javax.swing.JButton btnInsertGuest;
    private javax.swing.JButton btnResetKhachThue;
    private javax.swing.JButton btnSaveGuest;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cbCountrySide;
    private javax.swing.JComboBox<String> cbSex;
    private javax.swing.JComboBox<String> cbTypeFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spDob;
    private static javax.swing.JTable tbGuest;
    private javax.swing.JTextField tfGuestID;
    private javax.swing.JTextField tfGuestName;
    private javax.swing.JTextField tfInputFindGuest;
    private javax.swing.JTextField tfJob;
    private javax.swing.JTextField tfNumberID;
    private javax.swing.JTextField tfPermanentAddress;
    private javax.swing.JTextField tfPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
