/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.RoomBUS;
import DTO.DeviceDTO;
import DTO.RoomDTO;
import DTO.RoomTypeDTO;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author taipham
 */
public class QLPhongTroGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form QLPhongTroGUI
     */
    private static RoomDTO _roomDTO;
    private RoomBUS _roomBUS;
    private DefaultTableModel _tableModel;
    private static ArrayList<RoomDTO> _listRoom;
    private RoomTypeDTO _roomType;
    private ArrayList<DeviceDTO> _listDevice;
    private DefaultListModel _listModel = new DefaultListModel();

    public QLPhongTroGUI() {
        initComponents();
        this.setName("Phòng trọ");
        tbRoom.setFillsViewportHeight(true);
        tbKhachTro.setFillsViewportHeight(true);

        _roomDTO = new RoomDTO();
        _roomBUS = new RoomBUS();
        _roomType = new RoomTypeDTO();
        _listRoom = new ArrayList<>();
        _listDevice = new ArrayList<>();
        _listRoom = _roomBUS.getAllRoom();
        _tableModel = (DefaultTableModel) tbRoom.getModel();
        listDevice.setModel(_listModel);
        showTableRoom(_listRoom);

        setDataCbRoomTypeID("Thường");
        setPriceTfRoomPrice(cbRoomTypeID.getItemAt(0));

        btnSaveRoom.setEnabled(false);
        btnCancelRoom.setEnabled(false);
        tfRoomPrice.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tfMaKhachTro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfTenKhachTro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        spNgaySinh = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        cbQueQuan = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        tfNgheNghiep = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfMaPhongTro1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfDiemThoai = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfDiaChiThuongTru = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbPhai = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        tfCMND = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        spNgayThue = new javax.swing.JSpinner();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfRoomID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbRoomType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbRoomState = new javax.swing.JComboBox<>();
        cbQuantityGuest = new javax.swing.JComboBox<>();
        tfRoomPrice = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cbRoomTypeID = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listDevice = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        btnInsertRoom = new javax.swing.JButton();
        btnDeleteRoom = new javax.swing.JButton();
        btnEditRoom = new javax.swing.JButton();
        btnSaveRoom = new javax.swing.JButton();
        btnCancelRoom = new javax.swing.JButton();
        btnResetRoom = new javax.swing.JButton();
        btnThoat1 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        cbFindRoom = new javax.swing.JComboBox<>();
        tfFindInput = new javax.swing.JTextField();
        btnFindRoom = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRoom = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbKhachTro = new javax.swing.JTable();

        jButton1.setText("jButton1");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách thuê trọ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jLabel7.setText("Mã khách trọ:");

        jLabel8.setText("Tên khách trọ: ");

        jLabel9.setText("Ngày sinh:");

        spNgaySinh.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_WEEK));
        spNgaySinh.setEditor(new javax.swing.JSpinner.DateEditor(spNgaySinh, "dd/MM/yyyy"));

        jLabel10.setText("Quê quán:");

        cbQueQuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TP Hà Nội", "TP Hồ Chí Minh", "Tỉnh An Giang", "Tỉnh Bà Rịa - Vũng Tàu", "Tỉnh Bạc Liêu", "Tỉnh Bắc Giang", "Tỉnh Bắc Kạn", "Tỉnh Bắc Ninh", "Tỉnh Bến Tre", "Tỉnh Bình Dương", "Tỉnh Bình Định", "Tỉnh Bình Phước", "Tỉnh Bình Thuận", "Tỉnh Cao Bằng", "Tỉnh Cà Mau", "TP Cần Thơ", "TP Hải Phòng", "TP Đà Nẵng", "Tỉnh Gia Lai", "Tỉnh Hòa Bình", "Tỉnh Hà Giang", "Tỉnh Hà Nam", "Tỉnh Hà Tĩnh", "Tỉnh Hưng Yên", "Tỉnh Hải Dương", "Tỉnh Hậu Giang", "Tỉnh Điện Biên ", "Tỉnh Đắk Lắk", "Tỉnh Đắk Nông", "Tỉnh Đồng Nai", "Tỉnh Đồng Tháp", "Tỉnh Khánh Hòa", "Tỉnh Kiên Giang", "Tỉnh Kon Tum", "Tỉnh Lai Châu", "Tỉnh Long An", "Tỉnh Lào Cai", "Tỉnh Lâm Đồng", "Tỉnh Lạng Sơn", "Tỉnh Nam Định", "Tỉnh Nghệ An", "Tỉnh Ninh Bình", "Tỉnh Ninh Thuận", "Tỉnh Phú Thọ", "Tỉnh Phú Yên", "Tỉnh Quảng Bình", "Tỉnh Quảng Nam ", "Tỉnh Quảng Ngãi", "Tỉnh Quảng Ninh", "Tỉnh Quảng Trị", "Tỉnh Sóc Trăng", "Tỉnh Sơn La", "Tỉnh Thanh Hóa", "Tỉnh Thái Bình", "Tỉnh Thái Nguyên", "Tỉnh Thừa Thiên - Huế", "Tỉnh Tiền Giang", "Tỉnh Trà Vinh", "Tỉnh Tuyên Quang", "Tỉnh Tây Ninh", "Tỉnh Vĩnh Long", "Tỉnh Vĩnh Phúc", "Tỉnh Yên Bái" }));

        jLabel11.setText("Nghề nghiệp:");

        jLabel12.setText("Mã phòng trọ:");

        jLabel13.setText("Điện thoại:");

        jLabel14.setText("Địa chỉ thường trú: ");

        jLabel15.setText("Phái:");

        cbPhai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));
        cbPhai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPhaiActionPerformed(evt);
            }
        });

        jLabel16.setText("Số CMND:");

        jLabel17.setText("Ngày thuê:");

        spNgayThue.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_WEEK));
        spNgayThue.setEditor(new javax.swing.JSpinner.DateEditor(spNgayThue, "dd/MM/yyyy"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfMaKhachTro, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(tfMaPhongTro1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDiaChiThuongTru))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTenKhachTro, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPhai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(spNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfNgheNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDiemThoai)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfCMND)
                    .addComponent(spNgayThue)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfMaKhachTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTenKhachTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(spNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(tfCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPhai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfMaPhongTro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tfDiemThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tfNgheNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tfDiaChiThuongTru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(spNgayThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setPreferredSize(new java.awt.Dimension(1284, 514));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("QUẢN LÍ PHÒNG TRỌ");

        jPanel3.setBackground(new java.awt.Color(138, 213, 55));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phòng trọ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(553, 93));

        jLabel1.setText("Mã phòng trọ:");

        jLabel5.setText("Loại phòng:");

        cbRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thường", "Vip" }));
        cbRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoomTypeActionPerformed(evt);
            }
        });

        jLabel3.setText("Giá phòng:");

        jLabel4.setText("Tình trạng:");

        jLabel6.setText("Số người ở:");

        cbRoomState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Còn trống", "Đã thuê", "Đang sửa chữa" }));

        cbQuantityGuest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        cbQuantityGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQuantityGuestActionPerformed(evt);
            }
        });

        jLabel18.setText("Mã loại phòng:");

        cbRoomTypeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoomTypeIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbRoomState, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRoomID))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbRoomType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbQuantityGuest, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel18))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbRoomTypeID, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRoomPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cbRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(cbRoomTypeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRoomState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(tfRoomPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbQuantityGuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(5, 5, 5))
        );

        jPanel7.setBackground(new java.awt.Color(138, 213, 55));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tài sản", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel7.setInheritsPopupMenu(true);

        jScrollPane3.setViewportView(listDevice);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(138, 213, 55));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        btnInsertRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_themphong.png"))); // NOI18N
        btnInsertRoom.setText("Thêm");
        btnInsertRoom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInsertRoom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInsertRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertRoomActionPerformed(evt);
            }
        });

        btnDeleteRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_xoa.png"))); // NOI18N
        btnDeleteRoom.setText("Xóa");
        btnDeleteRoom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteRoom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnEditRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_sua.png"))); // NOI18N
        btnEditRoom.setText("Sửa");
        btnEditRoom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditRoom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditRoomActionPerformed(evt);
            }
        });

        btnSaveRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_save.png"))); // NOI18N
        btnSaveRoom.setText("Lưu");
        btnSaveRoom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaveRoom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSaveRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRoomActionPerformed(evt);
            }
        });

        btnCancelRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_huy.png"))); // NOI18N
        btnCancelRoom.setText("Hủy");
        btnCancelRoom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelRoom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelRoomActionPerformed(evt);
            }
        });

        btnResetRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_reset.png"))); // NOI18N
        btnResetRoom.setText("Reset");
        btnResetRoom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResetRoom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnResetRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetRoomActionPerformed(evt);
            }
        });

        btnThoat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_thoat.png"))); // NOI18N
        btnThoat1.setText("Thoát");
        btnThoat1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThoat1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInsertRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSaveRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnResetRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThoat1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInsertRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(138, 213, 55));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jLabel20.setText("Tìm kiếm theo:");

        cbFindRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã phòng", "Loại phòng", "Giá phòng", "Tình trạng phòng" }));
        cbFindRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFindRoomActionPerformed(evt);
            }
        });

        btnFindRoom.setText("Tìm kiếm");
        btnFindRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(cbFindRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfFindInput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFindRoom)
                .addGap(10, 10, 10))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cbFindRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFindInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindRoom))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(138, 213, 55));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách phòng trọ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel6.setLayout(new java.awt.BorderLayout());

        tbRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã  phòng trọ", "Mã loại phòng", "Loại phòng", "Tình trạng phòng", "Số người ở", "Giá phòng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRoomMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbRoom);
        if (tbRoom.getColumnModel().getColumnCount() > 0) {
            tbRoom.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbRoom.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(138, 213, 55));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách khách trọ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel4.setLayout(new java.awt.BorderLayout());

        tbKhachTro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã phòng trọ", "Mã khách trọ", "Tên khách trọ", "Ngày thuê"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbKhachTro);
        if (tbKhachTro.getColumnModel().getColumnCount() > 0) {
            tbKhachTro.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbKhachTro.getColumnModel().getColumn(0).setMaxWidth(40);
            tbKhachTro.getColumnModel().getColumn(1).setPreferredWidth(120);
            tbKhachTro.getColumnModel().getColumn(1).setMaxWidth(120);
            tbKhachTro.getColumnModel().getColumn(2).setPreferredWidth(120);
            tbKhachTro.getColumnModel().getColumn(2).setMaxWidth(120);
            tbKhachTro.getColumnModel().getColumn(4).setPreferredWidth(120);
            tbKhachTro.getColumnModel().getColumn(4).setMaxWidth(120);
        }

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(511, 511, 511)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void updateQuanity(String roomID){
        int totalRow = tbRoom.getRowCount();
        
        for(RoomDTO room : _listRoom){
            if(room.getRoomID().equals(roomID)){
                if(room.getRoomState() == 0){
                    int quanityGuest = room.getQuanityOfGuest();
                    room.setQuanityOfGuest(quanityGuest + 1);
                    if(room.getQuanityOfGuest() == QLGiaDichVuGUI.getRoomType(room.getRoomTypeID()).getMaxNumberGuest()){
                        room.setRoomState(1);
                    }
                    _roomDTO = room;
                }
            }
        }
        
        for(int i = 0; i < totalRow; ++i){
            if(tbRoom.getValueAt(i, 1).toString().equals(roomID)){
                tbRoom.setValueAt(getStateRoom(_roomDTO.getRoomState()), i, 4);
                tbRoom.setValueAt(_roomDTO.getQuanityOfGuest(), i, 5);
            }
        }
    }
    
    public static ArrayList<RoomDTO> getListRoom() {
        return _listRoom;
    }

    public void setDataCbRoomTypeID(String roomType) {
        String[] result = QLGiaDichVuGUI.getRoomTypeID(roomType);
        cbRoomTypeID.removeAllItems();
        for (int i = 0; i < result.length; ++i) {
            cbRoomTypeID.addItem(result[i]);
        }
    }

    public void setPriceTfRoomPrice(String roomTypeID) {
        _roomType = QLGiaDichVuGUI.getRoomType(roomTypeID);
        tfRoomPrice.setText(String.valueOf(_roomType.getRoomPrice()));
    }

    public static String getStateRoom(int i) {
        String status = "";
        if (i == 0) {
            status = "Còn trống";
        } else if (i == 1) {
            status = "Đã thuê";
        } else {
            status = "Đang sửa chữa";
        }
        return status;
    }

    public void showTableRoom(ArrayList<RoomDTO> listRoom) {
        int i = 1;
        for (RoomDTO room : listRoom) {
            _roomType = QLGiaDichVuGUI.getRoomType(room.getRoomTypeID());
            _tableModel.addRow(new Object[]{
                i++, room.getRoomID(), _roomType.getRoomTypeID(), _roomType.getRoomType(), getStateRoom(room.getRoomState()),
                room.getQuanityOfGuest(), _roomType.getRoomPrice()
            });
        }
    }

    public void showTableRoomUpdate() {
        int i = tbRoom.getRowCount() + 1;
        _roomDTO = _listRoom.get(_listRoom.size() - 1);
        _roomType = QLGiaDichVuGUI.getRoomType(_roomDTO.getRoomTypeID());
        _tableModel.addRow(new Object[]{
            i, _roomDTO.getRoomID(), _roomType.getRoomTypeID(), _roomType.getRoomType(), getStateRoom(_roomDTO.getRoomState()),
            _roomDTO.getQuanityOfGuest(), _roomType.getRoomPrice()
        });

    }

    private void cbPhaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPhaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPhaiActionPerformed

    private void cbFindRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFindRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFindRoomActionPerformed

    //chuyen doi trang thai phong sang so
    public int convertStateToInt(String status) {
        if (status.equals("Còn trống")) {
            return 0;
        } else if (status.equals("Đã thuê")) {
            return 1;
        } else {
            return 2;
        }
    }

    public void reset() {
        setEnable(true);
        btnInsertRoom.setEnabled(true);
        btnSaveRoom.setEnabled(false);
        btnCancelRoom.setEnabled(false);
        btnDeleteRoom.setEnabled(true);
        tfRoomID.setText("");
        cbRoomType.setSelectedIndex(0);
        cbRoomTypeID.removeAllItems();
        cbRoomState.setSelectedIndex(0);
        tfRoomPrice.setText("");
        cbQuantityGuest.setSelectedIndex(0);
        tbRoom.clearSelection();
        _listModel.removeAllElements();
        tfFindInput.setText("");
        cbFindRoom.setSelectedIndex(0);
    }

    //su kien them phong tro
    private void btnInsertRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertRoomActionPerformed
        //kiem tra thong tin nhap vao
        //chưa làm
        _roomDTO.setRoomID(tfRoomID.getText());
        _roomDTO.setRoomState(convertStateToInt(cbRoomState.getSelectedItem().toString()));
        _roomDTO.setQuanityOfGuest(cbQuantityGuest.getSelectedIndex());
        _roomDTO.setRoomTypeID(cbRoomTypeID.getSelectedItem().toString());

        if (_roomBUS.insertRoom(_roomDTO)) {
            JOptionPane.showMessageDialog(this, "Thêm vào database thành công", "Thêm phòng", JOptionPane.INFORMATION_MESSAGE);
            _listRoom.add(_roomDTO);
            showTableRoomUpdate();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm vào database thất bại", "Thêm loại phòng", JOptionPane.ERROR_MESSAGE);
        }
        reset();
        DangKiThuePhongGUI.showCbRoom(_listRoom);
        QLThietBiGUI.showRoomID(_listRoom);
    }//GEN-LAST:event_btnInsertRoomActionPerformed

    private void cbQuantityGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQuantityGuestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbQuantityGuestActionPerformed

    private void cbRoomTypeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoomTypeIDActionPerformed
        int i = cbRoomTypeID.getSelectedIndex();
        if (i != -1) {
            setPriceTfRoomPrice(cbRoomTypeID.getItemAt(i));
        }
    }//GEN-LAST:event_cbRoomTypeIDActionPerformed

    private void cbRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoomTypeActionPerformed
        setDataCbRoomTypeID(cbRoomType.getSelectedItem().toString());
        setPriceTfRoomPrice(cbRoomTypeID.getSelectedItem().toString());
    }//GEN-LAST:event_cbRoomTypeActionPerformed

    //bat su kien bam nut edit
    private void btnEditRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRoomActionPerformed
        setEnable(true);
        btnDeleteRoom.setEnabled(false);
        btnSaveRoom.setEnabled(true);
        btnCancelRoom.setEnabled(true);
        tfRoomID.setEnabled(false);
    }//GEN-LAST:event_btnEditRoomActionPerformed

    public void setEnable(boolean bool) {
        tfRoomID.setEnabled(bool);
        cbRoomType.setEnabled(bool);
        cbRoomTypeID.setEnabled(bool);
        cbRoomState.setEnabled(bool);
        cbQuantityGuest.setEnabled(bool);
        tfRoomPrice.setEnabled(bool);
    }

    //bat su kien nhap vao mot dong trong bang
    private void tbRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRoomMouseClicked
        int vt = tbRoom.getSelectedRow();
        if (vt != -1) {
            tfRoomID.setText(tbRoom.getValueAt(vt, 1).toString());
            cbRoomType.getModel().setSelectedItem(tbRoom.getValueAt(vt, 3));
            setDataCbRoomTypeID(cbRoomType.getSelectedItem().toString());
            cbRoomTypeID.getModel().setSelectedItem(tbRoom.getValueAt(vt, 2));
            cbRoomState.getModel().setSelectedItem(tbRoom.getValueAt(vt, 4));
            cbQuantityGuest.getModel().setSelectedItem(tbRoom.getValueAt(vt, 5));
            tfRoomPrice.setText(tbRoom.getValueAt(vt, 6).toString());
            
            _listDevice = QLThietBiGUI.getDevice(tbRoom.getValueAt(vt, 1).toString());
            
            _listModel.removeAllElements();
            for (DeviceDTO device : _listDevice) {
                _listModel.addElement(device.getDeviceName());
            }
        }
        btnInsertRoom.setEnabled(false);
        setEnable(false);
    }//GEN-LAST:event_tbRoomMouseClicked

    //su kien bam nut reset
    private void btnResetRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetRoomActionPerformed
        reset();
    }//GEN-LAST:event_btnResetRoomActionPerformed

    //su kien bam nut cancel
    private void btnCancelRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelRoomActionPerformed
        reset();
    }//GEN-LAST:event_btnCancelRoomActionPerformed

    public int getIndexListRoom(String roomID) {
        int len = _listRoom.size();
        for (int i = 0; i < len; ++i) {
            if (_listRoom.get(i).getRoomID().equals(roomID)) {
                return i;
            }
        }
        return -1;
    }

    //su kien bam nut luu
    private void btnSaveRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRoomActionPerformed
        int vt = tbRoom.getSelectedRow();
        if (vt != -1) {
            _roomDTO = _listRoom.get(getIndexListRoom(tbRoom.getValueAt(vt, 1).toString()));
            _roomDTO.setRoomState(convertStateToInt(cbRoomState.getSelectedItem().toString()));
            _roomDTO.setQuanityOfGuest(cbQuantityGuest.getSelectedIndex());
            _roomDTO.setRoomTypeID(cbRoomTypeID.getSelectedItem().toString());
            if (_roomBUS.updateRoom(_roomDTO)) {
                JOptionPane.showMessageDialog(this, "Update vào database thành công", "Update phòng trọ", JOptionPane.INFORMATION_MESSAGE);
                _roomType = QLGiaDichVuGUI.getRoomType(_roomDTO.getRoomTypeID());
                tbRoom.setValueAt(_roomDTO.getRoomTypeID(), vt, 2);
                tbRoom.setValueAt(_roomType.getRoomType(), vt, 3);
                tbRoom.setValueAt(_roomDTO.getRoomState(), vt, 4);
                tbRoom.setValueAt(_roomDTO.getQuanityOfGuest(), vt, 5);
                tbRoom.setValueAt(_roomType.getRoomPrice(), vt, 6);
            } else {
                JOptionPane.showMessageDialog(this, "Update vào database thất bại", "Update phòng trọ", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        reset();
        DangKiThuePhongGUI.showCbRoom(_listRoom);
    }//GEN-LAST:event_btnSaveRoomActionPerformed

    //su kien bam nut tim kiem
    private void btnFindRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindRoomActionPerformed
        String type = cbFindRoom.getSelectedItem().toString();
        String input = tfFindInput.getText();
        if (input.length() == 0) {
            JOptionPane.showMessageDialog(this, "Hãy điền thông tin tìm kiếm", "Tìm kiếm", JOptionPane.ERROR_MESSAGE);
            return;
        }
        switch (type) {
            case "Mã phòng":
                type = "MaPhongTro";
                break;
            case "Loại phòng":
                type = "LoaiPhong";
                break;
            case "Giá phòng":
                type = "GiaPhong";
                break;
            case "Tình trạng phòng":
                type = "TinhTrangPhong";
                break;
        }
        JFrame tmp = new JFrame();
        FindRoomDialog findDialog = new FindRoomDialog(tmp, true);
        if (type.equals("LoaiPhong")) {
            findDialog.showTableFindRoom(_roomBUS.findRoomByTypeRoom(input));
            findDialog.setVisible(true);
        } else if (type.equals("GiaPhong")) {
            findDialog.showTableFindRoom(_roomBUS.findRoomByRoomPrice(input));
            findDialog.setVisible(true);
        } else {
            findDialog.showTableFindRoom(_roomBUS.findRoomBy(type, input));
            findDialog.setVisible(true);
        }
    }//GEN-LAST:event_btnFindRoomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelRoom;
    private javax.swing.JButton btnDeleteRoom;
    private javax.swing.JButton btnEditRoom;
    private javax.swing.JButton btnFindRoom;
    private javax.swing.JButton btnInsertRoom;
    private javax.swing.JButton btnResetRoom;
    private javax.swing.JButton btnSaveRoom;
    private javax.swing.JButton btnThoat1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbFindRoom;
    private javax.swing.JComboBox<String> cbPhai;
    private javax.swing.JComboBox<String> cbQuantityGuest;
    private javax.swing.JComboBox<String> cbQueQuan;
    private javax.swing.JComboBox<String> cbRoomState;
    private javax.swing.JComboBox<String> cbRoomType;
    private javax.swing.JComboBox<String> cbRoomTypeID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listDevice;
    private javax.swing.JSpinner spNgaySinh;
    private javax.swing.JSpinner spNgayThue;
    private javax.swing.JTable tbKhachTro;
    private static javax.swing.JTable tbRoom;
    private javax.swing.JTextField tfCMND;
    private javax.swing.JTextField tfDiaChiThuongTru;
    private javax.swing.JTextField tfDiemThoai;
    private javax.swing.JTextField tfFindInput;
    private javax.swing.JTextField tfMaKhachTro;
    private javax.swing.JTextField tfMaPhongTro1;
    private javax.swing.JTextField tfNgheNghiep;
    private javax.swing.JTextField tfRoomID;
    private javax.swing.JTextField tfRoomPrice;
    private javax.swing.JTextField tfTenKhachTro;
    // End of variables declaration//GEN-END:variables
}
