/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlnhatro.gui;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 *
 * @author taipham
 */
public class QLNhaTroGUI extends javax.swing.JFrame {

    /**
     * Creates new form QLNhaTroGUI
     */
    
    static QLKhachThueTroGUI qlNguoiThueTroGUI;
    static QLPhongTroGUI qlPhongTroGUI;
    static DangKiThuePhongGUI dangKiThuePhong;
    static QLTaiChinhGUI qlTaiChinh;
    static QLThietBiGUI qlThietBi;
    static QLHopDongGUI hopDongGUI;
    static TraPhongGUI traPhongGUI;
    static QLChiTieu qlChiTieu;
    static QLGiaDichVuGUI qlGiaDichVuGUI;
    static DoiMatKhauGUI doiMatKhauGUI;
    static ThongKeGUI thongKeGUI;
    static ThonTinPhanMemGUI thongTinPhanMemGUI;
    
    public QLNhaTroGUI() {
        if(Login() == false){
            System.exit(0);
        }
        
        initComponents();
        //chinh full man hinh
        Dimension dimmax = Toolkit.getDefaultToolkit().getScreenSize();
        this.setMaximumSize(dimmax);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //////////////////
        
        qlNguoiThueTroGUI = new QLKhachThueTroGUI();
        qlPhongTroGUI = new QLPhongTroGUI();
        dangKiThuePhong = new DangKiThuePhongGUI();
        qlTaiChinh = new QLTaiChinhGUI();
        qlThietBi = new QLThietBiGUI();
        hopDongGUI = new QLHopDongGUI();
        traPhongGUI = new TraPhongGUI();
        qlChiTieu = new QLChiTieu();
        qlGiaDichVuGUI = new QLGiaDichVuGUI();
        doiMatKhauGUI = new DoiMatKhauGUI();
        thongKeGUI = new ThongKeGUI();
        thongTinPhanMemGUI = new ThonTinPhanMemGUI();
        
        qlNguoiThueTroGUI.setVisible(false);
        qlPhongTroGUI.setVisible(false);
        dangKiThuePhong.setVisible(false);
        qlTaiChinh.setVisible(false);
        qlThietBi.setVisible(false);
        hopDongGUI.setVisible(false);
        traPhongGUI.setVisible(false);
        qlChiTieu.setVisible(false);
        qlGiaDichVuGUI.setVisible(false);
        doiMatKhauGUI.setVisible(false);
        thongKeGUI.setVisible(false);
        thongTinPhanMemGUI.setVisible(false);
        
        
        panelKhungForm.add(qlNguoiThueTroGUI);
        panelKhungForm.add(qlPhongTroGUI);
        panelKhungForm.add(dangKiThuePhong);
        panelKhungForm.add(qlTaiChinh);
        panelKhungForm.add(qlThietBi);
        panelKhungForm.add(hopDongGUI);
        panelKhungForm.add(traPhongGUI);
        panelKhungForm.add(qlChiTieu);
        panelKhungForm.add(qlGiaDichVuGUI);
        panelKhungForm.add(doiMatKhauGUI);
        panelKhungForm.add(thongKeGUI);
        panelKhungForm.add(thongTinPhanMemGUI);
        
        setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        t = new javax.swing.JToolBar();
        pannel = new javax.swing.JPanel();
        btnKhachTro = new javax.swing.JButton();
        btnPhongTro = new javax.swing.JButton();
        btnTaiChinh = new javax.swing.JButton();
        btnTrangThietBi = new javax.swing.JButton();
        btnHopDong = new javax.swing.JButton();
        btnLichSu = new javax.swing.JButton();
        btnTaiKhoan = new javax.swing.JButton();
        btnThongTin = new javax.swing.JButton();
        btnTraPhong = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        panelKhungForm = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí phòng trọ");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        t.setRollover(true);

        pannel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản lí", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N
        pannel.setPreferredSize(new java.awt.Dimension(1305, 140));

        btnKhachTro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_khachtro.png"))); // NOI18N
        btnKhachTro.setText("Khách trọ");
        btnKhachTro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhachTro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhachTro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });

        btnPhongTro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_phongtro.png"))); // NOI18N
        btnPhongTro.setText("Phòng trọ");
        btnPhongTro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPhongTro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPhongTro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });

        btnTaiChinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_taichinh.png"))); // NOI18N
        btnTaiChinh.setText("Thu tiền ");
        btnTaiChinh.setActionCommand("Tài chính");
        btnTaiChinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTaiChinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTaiChinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });

        btnTrangThietBi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_mayquat.png"))); // NOI18N
        btnTrangThietBi.setText("Thiết bị");
        btnTrangThietBi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTrangThietBi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTrangThietBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });

        btnHopDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_hopdong.png"))); // NOI18N
        btnHopDong.setText("Hợp đồng");
        btnHopDong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHopDong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });

        btnLichSu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_chitieu.png"))); // NOI18N
        btnLichSu.setText("Chi tiêu");
        btnLichSu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLichSu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLichSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });

        btnTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_taikhoan.png"))); // NOI18N
        btnTaiKhoan.setText("Tài khoản");
        btnTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTaiKhoan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });

        btnThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_info.png"))); // NOI18N
        btnThongTin.setText("Thông tin");
        btnThongTin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongTin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });

        btnTraPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_check.png"))); // NOI18N
        btnTraPhong.setText("Trả phòng");
        btnTraPhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTraPhong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTraPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_dangki.png"))); // NOI18N
        jButton1.setText("Đăng kí");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_giadichvu.png"))); // NOI18N
        jButton2.setText("Giá dịch vụ");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_htongke.png"))); // NOI18N
        jButton4.setText("Thống kê");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Task(evt);
            }
        });

        javax.swing.GroupLayout pannelLayout = new javax.swing.GroupLayout(pannel);
        pannel.setLayout(pannelLayout);
        pannelLayout.setHorizontalGroup(
            pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKhachTro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPhongTro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTaiChinh, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrangThietBi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHopDong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTraPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLichSu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThongTin)
                .addGap(18, 18, 18))
        );
        pannelLayout.setVerticalGroup(
            pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelLayout.createSequentialGroup()
                .addGroup(pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTraPhong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pannelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTaiChinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKhachTro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPhongTro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHopDong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTrangThietBi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pannelLayout.createSequentialGroup()
                .addGroup(pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThongTin)
                    .addComponent(btnTaiKhoan)
                    .addComponent(jButton4)
                    .addGroup(pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnLichSu)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        t.add(pannel);

        panelKhungForm.setLayout(new javax.swing.BoxLayout(panelKhungForm, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t, javax.swing.GroupLayout.DEFAULT_SIZE, 1312, Short.MAX_VALUE)
                    .addComponent(panelKhungForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelKhungForm, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Task(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Task
        // TODO add your handling code here:
        String command = evt.getActionCommand();
        for (int i = 0; i < panelKhungForm.getComponents().length; i++)
        {
            Component cmpnt = panelKhungForm.getComponent(i);
            String n = cmpnt.getName();
            if(cmpnt.getName().equals(command)){
                cmpnt.setVisible(true);
            }
            else
            cmpnt.setVisible(false);
        }
    }//GEN-LAST:event_Task

    
    //////////////////////CODE In Hear///////////////////////////
    public boolean Login(){
        String userName = "", password = "";
        LoginGUI login = new LoginGUI(this, true);
        login.setVisible(true);
        userName = login.getUserName();
        password = login.getPassWord();
        if(userName.length() == 0 || password.length() == 0){
            return false;
        }
        
        //kiem tra username password
        login.setVisible(false);
        return true;
    }
    
    
    
    /**
     * @param ar
     * gs the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNhaTroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNhaTroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNhaTroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNhaTroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNhaTroGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHopDong;
    private javax.swing.JButton btnKhachTro;
    private javax.swing.JButton btnLichSu;
    private javax.swing.JButton btnPhongTro;
    private javax.swing.JButton btnTaiChinh;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnThongTin;
    private javax.swing.JButton btnTraPhong;
    private javax.swing.JButton btnTrangThietBi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelKhungForm;
    private javax.swing.JPanel pannel;
    private javax.swing.JToolBar t;
    // End of variables declaration//GEN-END:variables
}
