/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlnhatro.gui;

/**
 *
 * @author taipham
 */
public class QLThietBiGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form QLThietBi
     */
    public QLThietBiGUI() {
        initComponents();
        this.setName("Thiết bị");
        tbDanhSachThietBi.setFillsViewportHeight(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnThemKhachThue1 = new javax.swing.JButton();
        btnXoaKhachThue1 = new javax.swing.JButton();
        btnSuaKhachThue1 = new javax.swing.JButton();
        btnLuuKhachThue1 = new javax.swing.JButton();
        btnHuyKhachThue1 = new javax.swing.JButton();
        btnResetKhachThue1 = new javax.swing.JButton();
        btnThoat1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDanhSachThietBi = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbPhongTro = new javax.swing.JComboBox<>();
        chbMayQuat = new javax.swing.JCheckBox();
        chbMayLanh = new javax.swing.JCheckBox();
        chbBanGhe = new javax.swing.JCheckBox();
        chbDenDien = new javax.swing.JCheckBox();
        chbTuDo = new javax.swing.JCheckBox();
        chbBepGa = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        tfThietBiKhac = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbThietBi = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbTinhTrang = new javax.swing.JComboBox<>();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("QUẢN LÍ THIẾT BỊ");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        btnThemKhachThue1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_themphong.png"))); // NOI18N
        btnThemKhachThue1.setText("Thêm");
        btnThemKhachThue1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThemKhachThue1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnXoaKhachThue1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_xoa.png"))); // NOI18N
        btnXoaKhachThue1.setText("Xóa");
        btnXoaKhachThue1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoaKhachThue1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnSuaKhachThue1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_sua.png"))); // NOI18N
        btnSuaKhachThue1.setText("Sửa");
        btnSuaKhachThue1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSuaKhachThue1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnLuuKhachThue1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_save.png"))); // NOI18N
        btnLuuKhachThue1.setText("Lưu");
        btnLuuKhachThue1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLuuKhachThue1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnHuyKhachThue1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_huy.png"))); // NOI18N
        btnHuyKhachThue1.setText("Hủy");
        btnHuyKhachThue1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuyKhachThue1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnResetKhachThue1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_reset.png"))); // NOI18N
        btnResetKhachThue1.setText("Reset");
        btnResetKhachThue1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResetKhachThue1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnThoat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_thoat.png"))); // NOI18N
        btnThoat1.setText("Thoát");
        btnThoat1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThoat1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemKhachThue1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoaKhachThue1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSuaKhachThue1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLuuKhachThue1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHuyKhachThue1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnResetKhachThue1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThoat1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemKhachThue1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaKhachThue1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaKhachThue1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuuKhachThue1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuyKhachThue1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetKhachThue1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách thiết bị", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        tbDanhSachThietBi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã phòng trọ", "Máy quạt", "Máy lạnh", "Bàn, ghế", "Đèn điện ", "Tủ đồ", "Bếp ga", "Thiết bị khác"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbDanhSachThietBi);
        if (tbDanhSachThietBi.getColumnModel().getColumnCount() > 0) {
            tbDanhSachThietBi.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbDanhSachThietBi.getColumnModel().getColumn(0).setMaxWidth(40);
            tbDanhSachThietBi.getColumnModel().getColumn(2).setMaxWidth(70);
            tbDanhSachThietBi.getColumnModel().getColumn(3).setPreferredWidth(70);
            tbDanhSachThietBi.getColumnModel().getColumn(3).setMaxWidth(70);
            tbDanhSachThietBi.getColumnModel().getColumn(4).setPreferredWidth(70);
            tbDanhSachThietBi.getColumnModel().getColumn(4).setMaxWidth(70);
            tbDanhSachThietBi.getColumnModel().getColumn(5).setPreferredWidth(70);
            tbDanhSachThietBi.getColumnModel().getColumn(5).setMaxWidth(70);
            tbDanhSachThietBi.getColumnModel().getColumn(6).setPreferredWidth(70);
            tbDanhSachThietBi.getColumnModel().getColumn(6).setMaxWidth(70);
            tbDanhSachThietBi.getColumnModel().getColumn(7).setPreferredWidth(70);
            tbDanhSachThietBi.getColumnModel().getColumn(7).setMaxWidth(70);
        }

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin thiết bị", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jLabel1.setText("Phòng:");

        cbPhongTro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        chbMayQuat.setText("Máy quạt");
        chbMayQuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbMayQuatActionPerformed(evt);
            }
        });

        chbMayLanh.setText("Máy lạnh");

        chbBanGhe.setText("Bàn, ghế");

        chbDenDien.setText("Đèn điện");

        chbTuDo.setText("Tủ đồ");

        chbBepGa.setText("Bếp ga");

        jLabel3.setText("Thiết bị khác: ");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tình trạng thiết bị", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jLabel5.setText("Tên thiết bị:");

        cbThietBi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Máy quạt", "Máy lạnh ", "Bàn, ghế", "Đèn điện", "Tủ đồ", "Bếp ga" }));

        jLabel6.setText("Tình trạng:");

        cbTinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bình thường", "Cần sửa chữa", "Hỏng" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbPhongTro, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfThietBiKhac))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(chbMayQuat)
                                .addGap(18, 18, 18)
                                .addComponent(chbMayLanh)
                                .addGap(18, 18, 18)
                                .addComponent(chbBanGhe)))
                        .addGap(18, 18, 18)
                        .addComponent(chbDenDien)
                        .addGap(18, 18, 18)
                        .addComponent(chbTuDo)
                        .addGap(18, 18, 18)
                        .addComponent(chbBepGa))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbPhongTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbMayQuat)
                    .addComponent(chbMayLanh)
                    .addComponent(chbBanGhe)
                    .addComponent(chbDenDien)
                    .addComponent(chbTuDo)
                    .addComponent(chbBepGa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfThietBiKhac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(313, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(286, 286, 286))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(549, 549, 549))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chbMayQuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbMayQuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbMayQuatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyKhachThue1;
    private javax.swing.JButton btnLuuKhachThue1;
    private javax.swing.JButton btnResetKhachThue1;
    private javax.swing.JButton btnSuaKhachThue1;
    private javax.swing.JButton btnThemKhachThue1;
    private javax.swing.JButton btnThoat1;
    private javax.swing.JButton btnXoaKhachThue1;
    private javax.swing.JComboBox<String> cbPhongTro;
    private javax.swing.JComboBox<String> cbThietBi;
    private javax.swing.JComboBox<String> cbTinhTrang;
    private javax.swing.JCheckBox chbBanGhe;
    private javax.swing.JCheckBox chbBepGa;
    private javax.swing.JCheckBox chbDenDien;
    private javax.swing.JCheckBox chbMayLanh;
    private javax.swing.JCheckBox chbMayQuat;
    private javax.swing.JCheckBox chbTuDo;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDanhSachThietBi;
    private javax.swing.JTextField tfThietBiKhac;
    // End of variables declaration//GEN-END:variables
}
